#!/bin/bash
#
# Points *.${DEV_DOMAIN} at 127.0.0.1 using the stack's dnsmasq.
#
# Only the development domain is routed. The rest of the machine's DNS is left
# alone, so the internet keeps working when the container is stopped.
#
set -euo pipefail

cd "$(dirname "$(readlink -f "$0")")"

# --- Settings read from .env ---
if [ -f .env ]; then
    set -a +u
    . ./.env
    set +a -u
fi

DEV_DOMAIN="${DEV_DOMAIN:-}"
DNS_PORT="${DNS_PORT:-5354}"
DNS_ADDR="127.0.0.1"

RESOLVED_CONF="/etc/systemd/resolved.conf.d/50-php-devforge.conf"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; BLUE='\033[0;34m'; NC='\033[0m'
info()  { echo -e "${GREEN}[INFO]${NC} $1"; }
warn()  { echo -e "${YELLOW}[AVISO]${NC} $1"; }
err()   { echo -e "${RED}[ERROR]${NC} $1"; }
title() { echo -e "${BLUE}$1${NC}"; }

# This script needs sudo. When there is no terminal to type the password in
# (run from an editor or a pipe), say so clearly instead of failing with a
# cryptic sudo error.
require_sudo() {
    if sudo -n true 2>/dev/null; then
        return 0
    fi
    if [ ! -t 0 ]; then
        err "sudo is required, but there is no terminal to type the password in."
        echo ""
        echo "  Run this script directly in a terminal:"
        echo "      cd $(pwd) && ./setup-local-dns.sh"
        echo ""
        echo "  Or cache your password in the terminal first and try again:"
        echo "      sudo -v"
        echo ""
        exit 1
    fi
}

require_domain() {
    if [ -z "$DEV_DOMAIN" ]; then
        err "Could not read 'DEV_DOMAIN' from .env."
        exit 1
    fi
}

# Detects which tool can do per-domain DNS.
# systemd-resolved is checked BEFORE NetworkManager: when resolved is active,
# NetworkManager delegates DNS to it anyway, and only resolved can route a
# single domain (and use a port other than 53).
detect_backend() {
    if [ "$(uname -s)" = "Darwin" ]; then
        echo "macos"
    elif systemctl is-active --quiet systemd-resolved 2>/dev/null; then
        echo "resolved"
    else
        echo "unsupported"
    fi
}

manual_instructions() {
    warn "systemd-resolved is not active on this system."
    echo ""
    echo "  Your DNS configuration will not be touched: without systemd-resolved"
    echo "  there is no safe way to route a single domain, and changing all of it"
    echo "  could leave you with no internet when the container is stopped."
    echo ""
    echo "  Options:"
    echo "    1. Enable systemd-resolved:  sudo systemctl enable --now systemd-resolved"
    echo "    2. Or add each site by hand to /etc/hosts:"
    echo "         127.0.0.1  misitio.${DEV_DOMAIN}"
    echo "       (no wildcards: every subdomain must be listed)"
    echo ""
}

install_resolved() {
    require_sudo
    info "Configuring systemd-resolved (only for *.${DEV_DOMAIN})"
    sudo mkdir -p /etc/systemd/resolved.conf.d
    sudo tee "$RESOLVED_CONF" >/dev/null <<EOF
# Generated by PHP DevForge - do not edit by hand.
# To undo:  ./setup-local-dns.sh --remove
#
# 'Domains=~domain' means: send ONLY that domain to this server.
# Every other query keeps going to your normal DNS.
[Resolve]
DNS=${DNS_ADDR}:${DNS_PORT}
Domains=~${DEV_DOMAIN}
EOF
    sudo systemctl restart systemd-resolved
    info "✓ Done. Only *.${DEV_DOMAIN} goes through dnsmasq (${DNS_ADDR}:${DNS_PORT})"
}

install_macos() {
    require_sudo
    info "Configuring /etc/resolver/${DEV_DOMAIN}"
    sudo mkdir -p /etc/resolver
    sudo tee "/etc/resolver/${DEV_DOMAIN}" >/dev/null <<EOF
nameserver ${DNS_ADDR}
port ${DNS_PORT}
EOF
    sudo dscacheutil -flushcache
    sudo killall -HUP mDNSResponder 2>/dev/null || true
    info "✓ Done. Only *.${DEV_DOMAIN} goes through dnsmasq (${DNS_ADDR}:${DNS_PORT})"
}

do_install() {
    require_domain
    title "================================"
    title "   PHP DevForge - local DNS"
    title "================================"
    echo ""
    info "Domain:   *.${DEV_DOMAIN}"
    info "dnsmasq:  ${DNS_ADDR}:${DNS_PORT}"
    echo ""
    case "$(detect_backend)" in
        macos)       install_macos ;;
        resolved)    install_resolved ;;
        unsupported) manual_instructions; exit 1 ;;
    esac
    echo ""
    do_test || true
    echo ""
    warn "To undo everything:  ./setup-local-dns.sh --remove"
}

# No require_domain: undoing has to work when .env is already gone, which is
# exactly the state you are in while cleaning up.
do_remove() {
    require_sudo
    case "$(detect_backend)" in
        macos)
            if [ -z "$DEV_DOMAIN" ]; then
                err "Without DEV_DOMAIN in .env I cannot tell which resolver file is ours."
                echo "  Remove it by hand:  sudo rm /etc/resolver/<your-domain>" >&2
                exit 1
            fi
            if [ -f "/etc/resolver/${DEV_DOMAIN}" ]; then
                sudo rm -f "/etc/resolver/${DEV_DOMAIN}"
                sudo dscacheutil -flushcache
                sudo killall -HUP mDNSResponder 2>/dev/null || true
                info "✓ Removed /etc/resolver/${DEV_DOMAIN}"
            else
                info "Nothing to remove."
            fi
            ;;
        resolved)
            if [ -f "$RESOLVED_CONF" ]; then
                sudo rm -f "$RESOLVED_CONF"
                sudo systemctl restart systemd-resolved
                info "✓ Removed $RESOLVED_CONF"
            else
                info "Nothing to remove."
            fi
            ;;
        *) info "Nothing to remove on this system." ;;
    esac
}

do_status() {
    require_domain
    title "Current state"
    echo ""
    case "$(detect_backend)" in
        macos)
            if [ -f "/etc/resolver/${DEV_DOMAIN}" ]; then
                info "Configured in /etc/resolver/${DEV_DOMAIN}:"
                sed 's/^/    /' "/etc/resolver/${DEV_DOMAIN}"
            else
                warn "Not configured. Run: ./setup-local-dns.sh"
            fi
            ;;
        resolved)
            if [ -f "$RESOLVED_CONF" ]; then
                info "Configured in $RESOLVED_CONF:"
                grep -vE '^\s*#|^\s*$' "$RESOLVED_CONF" | sed 's/^/    /'
            else
                warn "Not configured. Run: ./setup-local-dns.sh"
            fi
            ;;
        *) warn "systemd-resolved is not active on this system." ;;
    esac
    echo ""
    info "Is dnsmasq listening on ${DNS_ADDR}:${DNS_PORT}?"
    if docker ps --filter name=dnsmasq --filter status=running --format '{{.Names}}' 2>/dev/null | grep -q dnsmasq; then
        echo "    ✓ dnsmasq container running"
    else
        echo "    ✗ dnsmasq container stopped  (docker compose up -d dnsmasq)"
    fi
}

# Resolve through the real system path.
# nslookup/dig are avoided on purpose: on macOS they ignore /etc/resolver and
# would report a false failure. getent and dscacheutil use the system resolver.
resolve_host() {
    if [ "$(uname -s)" = "Darwin" ]; then
        dscacheutil -q host -a name "$1" 2>/dev/null | awk '/^ip_address:/{print $2; exit}'
    else
        getent hosts "$1" 2>/dev/null | awk '{print $1; exit}'
    fi
}

do_test() {
    require_domain
    local host="test.${DEV_DOMAIN}" ok=0

    info "Checking your domain (${host})..."
    local got; got=$(resolve_host "$host" || true)
    if [ "$got" = "127.0.0.1" ]; then
        echo "    ✓ ${host} -> 127.0.0.1"
    else
        echo "    ✗ ${host} -> ${got:-no answer}   (is dnsmasq running?)"
        ok=1
    fi

    info "Checking that the internet still works..."
    got=$(resolve_host github.com || true)
    if [ -n "$got" ]; then
        echo "    ✓ github.com -> ${got}"
    else
        echo "    ✗ github.com does not resolve"
        ok=1
    fi
    return $ok
}

usage() {
    cat <<EOF
PHP DevForge - local DNS configuration

Usage: $0 [OPTION]

No options            Point *.${DEV_DOMAIN:-your-domain} -> 127.0.0.1
  -r, --remove        Undo the change (removes a single file)
  -s, --status        Show the current configuration
  -t, --test          Check resolution
  -h, --help          This help

Only your development domain is routed. The rest of your DNS is untouched.
EOF
}

case "${1:-}" in
    -h|--help)    usage ;;
    -r|--remove)  do_remove ;;
    -s|--status)  do_status ;;
    -t|--test)    do_test ;;
    "")           do_install ;;
    *)            err "Unknown option: $1"; echo ""; usage; exit 1 ;;
esac
